### PR TITLE
adding tests for new unique loggers

### PR DESCRIPTION
**Pull request by davelkan-zz**
Added tests for unique throttler.

Tests confirm the expected behavior of the unique logger. Have run and confirmed tests do not fail. Will be making a second PR to our codebase so we don't have to remerge this branch. This PR is really for getting this shipped upstream

### CODE REVIEW

**Review by paulbovbel — APPROVED** [review]

**Review by ayrton04 — APPROVED** [review]

**Comment by ayrton04** [comment]
Kicking the build farm.

**Comment by ayrton04** [comment]
Oh, you are PR-ing into your other branch, and not into lunar-devel-locus. Was that intentional?

**Comment by ayrton04** [comment]
Is this for 18.2?

**Comment by davelkan-zz** [comment]
@ayrton04 this was a request upstream. I'm making the changes to the branch i am merging upstream

**Pull request merged**
