### PR TITLE
Initialize publisher/subscriber options in impl constructors

### PR DESCRIPTION
**Pull request by abencz**
Prevents misconfigured connections from being added to a topic before
topic configuration is complete.

### CODE REVIEW

**Comment by abencz** [comment]
My attempt at a proper solution. Connection options are initialized in their respective `__init__` methods instead of by calling setters on the topic instance afterwards.

This changes a subtle behavior when creating multiple publishers/subscribers for the same topic where options to later instances override those of previous instances. I hope we don't rely on this behavior anywhere - that would be pretty gross.

**Comment by paulbovbel** [comment]
> I hope we don't rely on this behavior anywhere - that would be pretty gross.

Yes, this is different, but no worse than the current behaviour (last publisher wins).

Please add to the list of patches in https://locusrobotics.atlassian.net/browse/RST-3426 once merged to devel

**Review by ayrton04 — APPROVED** [review]
Nice.

**Review by MJohnson459 — APPROVED** [review]

**Comment by abencz** [comment]
> Please add to the list of patches in https://locusrobotics.atlassian.net/browse/RST-3426 once merged to devel

@paulbovbel I think this is the wrong Jira. Did you mean: https://locusrobotics.atlassian.net/browse/RST-1955

**Pull request merged**
